
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0018:Comparison of floating point numbers with equality operator", Justification = "<Pending>", Scope = "member", Target = "~M:DarkMultiPlayer.WarpWorker.SubpaceDisplayEntrySorter(DarkMultiPlayer.SubspaceDisplayEntry,DarkMultiPlayer.SubspaceDisplayEntry)~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0018:Comparison of floating point numbers with equality operator", Justification = "<Pending>", Scope = "member", Target = "~M:DarkMultiPlayer.WarpWorker.SubspaceComparer(System.Int32,System.Int32)~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0082:Parameter has the same name as a member and hides it", Justification = "<Pending>", Scope = "member", Target = "~M:DarkMultiPlayer.WarpWorker.HandleReplyVote(System.Int32,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0022:A catch clause that catches System.Exception and has an empty body", Justification = "<Pending>", Scope = "member", Target = "~M:DarkMultiPlayer.VesselWorker.FixedUpdate")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0022:A catch clause that catches System.Exception and has an empty body", Justification = "<Pending>", Scope = "member", Target = "~M:DarkMultiPlayer.NetworkWorker.CheckInitialDisconnection")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0022:A catch clause that catches System.Exception and has an empty body", Justification = "<Pending>", Scope = "member", Target = "~M:DarkMultiPlayer.NetworkWorker.TerminateThreads")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0022:A catch clause that catches System.Exception and has an empty body", Justification = "<Pending>", Scope = "member", Target = "~M:DarkMultiPlayer.NetworkWorker.HandleHandshakeReply(System.Byte[])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0018:Comparison of floating point numbers with equality operator", Justification = "<Pending>", Scope = "member", Target = "~M:DarkMultiPlayer.PlayerStatusWindow.Update")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0018:Comparison of floating point numbers with equality operator", Justification = "<Pending>", Scope = "member", Target = "~M:DarkMultiPlayer.VesselUpdate.Apply(DarkMultiPlayer.PosistionStatistics,System.Collections.Generic.Dictionary{System.Guid,DarkMultiPlayer.VesselCtrlUpdate},DarkMultiPlayer.VesselUpdate,DarkMultiPlayer.VesselUpdate,DarkMultiPlayer.Settings)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0117:Local variable has the same name as a member and hides it", Justification = "<Pending>", Scope = "member", Target = "~M:DarkMultiPlayer.Settings.LoadSettings")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0117:Local variable has the same name as a member and hides it", Justification = "<Pending>", Scope = "member", Target = "~M:DarkMultiPlayer.CraftLibraryWorker.SaveCraftFile(DarkMultiPlayerCommon.CraftType,System.String,System.Byte[])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0082:Parameter has the same name as a member and hides it", Justification = "<Pending>", Scope = "member", Target = "~M:DarkMultiPlayer.DMPModInterface.DMPRun(DarkMultiPlayer.NetworkWorker)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0082:Parameter has the same name as a member and hides it", Justification = "<Pending>", Scope = "member", Target = "~M:DarkMultiPlayer.Button.attachEventHandler(System.Reflection.EventInfo,System.String,System.Object)~System.Delegate")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:DarkMultiPlayer.Button.detachEventHandler(System.Reflection.EventInfo,System.Delegate,System.Object)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Redundancies in Symbol Declarations", "RECS0001:Class is declared partial but has only one part", Justification = "<Pending>", Scope = "type", Target = "~T:DarkMultiPlayer.PopupMenuDrawable")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Common Practices and Code Improvements", "RECS0030:Suggests using the class declaring a static function when calling it", Justification = "<Pending>", Scope = "member", Target = "~M:DarkMultiPlayer.DebugWindow.DrawContent(System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Common Practices and Code Improvements", "RECS0030:Suggests using the class declaring a static function when calling it", Justification = "<Pending>", Scope = "member", Target = "~M:DarkMultiPlayer.LineRendererDebug.Destroy")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:DarkMultiPlayer.Button.mouseEntered(System.Object)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:DarkMultiPlayer.Button.mouseLeft(System.Object)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0082:Parameter has the same name as a member and hides it", Justification = "<Pending>", Scope = "member", Target = "~M:DarkMultiPlayer.Button.detachEventHandler(System.Reflection.EventInfo,System.Delegate,System.Object)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0018:Comparison of floating point numbers with equality operator", Justification = "<Pending>", Scope = "member", Target = "~M:DarkMultiPlayer.SafetyBubblePosition.Equals(System.Object)~System.Boolean")]

